### ISSUE TITLE
Mismatched Number of Dihedrals and Central Cartesians when Running on a Dimer. 

### ISSUE THREAD

**Issue by RMCrean** [AG-Peter/encodermap#12]
Hey, 

This method looks really nice, and I am hoping to apply it on my system of interest. Unfortunately, I am running into an error if I try to analyse simulations of a dimer as opposed to just a monomer. 

I am using a modified form of a template python script you provided in this [pull request](https://github.com/AG-Peter/encodermap/issues/5). I have a large conformational change to study so I would like to use the AngleDihedralCartesianEncoderMap class. (The python script is in the zip file.)

Taking just a monomer from my simulations, everything runs fine. However, when I run the script with a dimer (it’s from the same simulations I just kept more residues in the input trajectory and of course updated the reference PDB as well) I get the following error:

(EncoderMap) [x_rorcr@berzelius001 SonMTA]$ python EncoderMap_V1.py
Loading Cartesians...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:00<00:00, 7186.70it/s]
Calculating dihedrals...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:00<00:00, 3633.27it/s]
/home/x_rorcr/.conda/envs/EncoderMap/lib/python3.7/site-packages/MDAnalysis/analysis/dihedrals.py:336: DeprecationWarning: The `angle` attribute was deprecated in MDAnalysis 2.0.0 and will be removed in MDAnalysis 3.0.0. Please use `results.angles` instead
  warnings.warn(wmsg, DeprecationWarning)
Calculating angles...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:00<00:00, 4179.47it/s]
Calculating lengths...
Traceback (most recent call last):
  File "EncoderMap_V1.py", line 32, in <module>
    moldata = em.MolData(selected_atoms) #, cache_path="data/{}/cache".format(molname)
  File "/home/x_rorcr/.conda/envs/EncoderMap/lib/python3.7/site-packages/encodermap/moldata.py", line 157, in __init__
    assert self.dihedrals.shape[1] == self.central_cartesians.shape[1] - 3
AssertionError
#############################################################################

I’ve tried to do a small bit of troubleshooting already by printing the lengths of each component just before the assert tests in moldata.py as follows:
print(f"self.lengths.shape[1] is: {self.lengths.shape[1]}")
print(f"(self.central_cartesians.shape[1] - 1) is: {(self.central_cartesians.shape[1] - 1)}")
print("")
print(f"self.angles.shape[1] is: {self.angles.shape[1]}")
print(f"(self.central_cartesians.shape[1] - 2) is: {(self.central_cartesians.shape[1] - 2)}")
print("")
print(f"self.dihedrals.shape[1] is: {self.dihedrals.shape[1]}")
print(f"(self.central_cartesians.shape[1] - 3) is: {(self.central_cartesians.shape[1] - 3)}")

**The output from this is:**
self.lengths.shape[1] is: 998
(self.central_cartesians.shape[1] - 1) is: 998

self.angles.shape[1] is: 997
(self.central_cartesians.shape[1] - 2) is: 997

self.dihedrals.shape[1] is: 993
(self.central_cartesians.shape[1] - 3) is: 996

So there is a mismatch of only 3, which makes me think the issue could be in how the terminal residues at the end of the first domain and start of the second domain are being treated?  

One other potentially useful piece of information is that my trajectory was generated with AmberMD using an Amber force field (ff14SB), so perhaps this is a naming convention issue with the terminal atom names? I am not sure if that is the case though otherwise there should also be issues in the monomer version too right? 

I’ve added my reference pdb version for both the monomer and dimer. In the dimer, the numbering gap is on purpose, as there a ligand between the two domains in the simulations (but removed here in both the trajectory and simulation).  If you would like, I can also provide a small trajectory file. 

Do you have any suggestions on what could be going wrong? 
[EncoderMap_Issues.zip](https://github.com/AG-Peter/encodermap/files/7241959/EncoderMap_Issues.zip)

Thanks!

**Comment by TobiasLe** [comment]
Hi, 

the AngleDihedralCartesianEncoderMap class (and moldata) only support one contentious chain of atoms, not two separate molecules. The problem ist that when the Cartesian coordinates are reconstructed from the dihedrals, there is no way to reconstruct the relative position of two unconnected molecules from the dihedrals.

Probably the best you can do is to analyse both molecules separately.

**Comment by RMCrean** [comment]
Hey and thanks for getting back to me and explaining the situation. I will have a look and see if I can get something meaningful by treating the domains separately then. 
Cheers.
