### ISSUE TITLE
Regularization

### ISSUE THREAD

**Issue by muammar** [AG-Peter/encodermap#2]
I read the paper that explains encodermap, and there is something I don't understand in the regularization part. In Eq. (6) the regularization is defined as:

![Screenshot from 2019-05-10 11-36-06](https://user-images.githubusercontent.com/954209/57549279-f302cd80-7317-11e9-9fc1-d74dc70cb4b3.png)

However, when you inspect the [cost function calculation](https://github.com/AG-Peter/encodermap/blob/456d1020698c6d8dc89643235dabdf15f9573a05/encodermap/autoencoder.py#L143), it seems to me as if only [L2 regularization](https://www.tensorflow.org/api_docs/python/tf/contrib/layers/l2_regularizer) is applied to the weights of the network:

```
if self.p.l2_reg_constant != 0:
    reg_cost = tf.losses.get_regularization_loss()
    tf.summary.scalar("reg_cost", reg_cost)
    cost += reg_cost
```

Where is the penalization that restricts the activation in the bottleneck layer computed in your encodermap implementation? Reading the documentation of `tf.contib.layers.l2_regularizers` it clearly states that just the neural network weights are involved in this regularization. I would appreciate your comments on this :).

Thanks. 

Note: I myself do not use tensorflow but Pytorch. Is there something I am missing?

**Comment by TobiasLe** [comment]
This is the part of the code you are looking for:

```python
if self.p.center_cost_scale != 0:
                center_cost = tf.reduce_mean(tf.square(self.latent))
                tf.summary.scalar("center_cost", center_cost)
                cost += self.p.center_cost_scale * center_cost
```
In the code I called this part of the cost function "center_cost" because it keeps the low-dimensional representation centered around 0. Sorry if this naming might be confusing.

Let me know if you have any other questions.

**Comment by muammar** [comment]
Thanks for your reply. I should have kept reading the code instead. I will proceed to close this issue.
