### ISSUE TITLE
Dimensions of input and encoded data

### ISSUE THREAD

**Issue by patwin2** [AG-Peter/encodermap#28]
I'm running encodermap on a 500,000 frame simulation of a 394 aa protein. I'm using central_dihedrals as the CV.

When I print the shape of the highD data, I get (500000 1179), which makes sense.
When I print the shape of the lowD encoded data, I get (16000 2). But in the documentation it says the the encoded data should have the same number of rows as the input data. Am I misunderstanding something? My code is below.

-------------------------------------------------------------------------------------------------------------------

traj = em.SingleTraj("/PATH/trajectory.dcd", "/PATH/topology.pdb")

print(traj)

central_dihedrals = em.loading.features.CentralDihedrals(traj.top)
highd = traj.load_CV(central_dihedrals)
print(traj.central_dihedrals.shape)

parameters = em.Parameters()
parameters.main_path = em.misc.run_path("runs/my_data")
parameters.n_steps = 1000
parameters.dist_sig_parameters = (400, 10, 5, 1, 2, 5)
parameters.periodicity = 2*pi

e_map = em.EncoderMap(parameters, highd)
e_map.train()

low_d_projection = e_map.encode(data = highd)

print(low_d_projection.shape)

----------------------------------------------------------------------------------------------------------------------------

**Comment by kevinsawade** [comment]
Hello patwin2,

You're right. The lowd projection should have the same number of input features. I will look into your issue.

**Comment by kevinsawade** [comment]
Hello patwin2,

I was not able to reproduce your issue with version 3.0.0 of EncoderMap. I could not use a training set of 500,000 frames, as my PC kept crashing. I could get 250,000 frames to work and was not able to reproduce your issue. Find the code, I used to reproduce here:

https://gist.github.com/kevinsawade/5d3006dfa2920e27aa39bf73467dd77f

In this notebook, there is also a fix, that you can try. Can you try to split/chunk your input array and see, whether the issue persists?

```python
low_d_projection = []

for i, highd_subset in enumerate(np.array_split(highd, 15)):
  lowd_subset = e_map.encode(highd_subset)

  print(f"At step {i}, the subset has shape: {highd_subset.shape}. Encoded lowd subset has shape {lowd_subset.shape}")

  low_d_projection.append(lowd_subset)

low_d_projection = np.vstack(low_d_projection)
print(f"Final projection has shape {low_d_projection.shape}")
```

**Comment by patwin2** [comment]
Your suggested fix worked. Here's my code:

---------------------------------------------------------------------------------------------------------------------
traj = em.SingleTraj("/PATH/trajectory.dcd", "/PATH/topology.pdb")

print(traj)

central_dihedrals = em.loading.features.CentralDihedrals(traj.top)
highd = traj.load_CV(central_dihedrals)
print(traj.central_dihedrals.shape)

parameters = em.Parameters()
parameters.main_path = em.misc.run_path("runs/my_data")
parameters.n_steps = 1000
parameters.dist_sig_parameters = (4.5, 12, 6, 1, 2, 6)
parameters.periodicity = 2*pi

e_map = em.EncoderMap(parameters, traj.central_dihedrals)
e_map.train()

low_d_projection = []

for i, highd_subset in enumerate(np.array_split(traj.central_dihedrals, 15)):
  lowd_subset = e_map.encode(highd_subset)

  print(f"At step {i}, the subset has shape: {highd_subset.shape}. Encoded lowd subset has shape {lowd_subset.shape}")

  low_d_projection.append(lowd_subset)

low_d_projection = np.vstack(low_d_projection)
print(f"Final projection has shape {low_d_projection.shape}")
-------------------------------------------------------------------------------------------------------------------------------

traj.central_dihedrals.shape is (500,000 1179)
low_d_projection.shape is (500,000 2)

Thanks.
