### ISSUE TITLE
Checkpoints not created

### ISSUE THREAD

**Issue by Monte95** [AG-Peter/encodermap#4]
Goodmorning. After successfully installing docker and running the tutorial 02_Advanced_Usage-Asp7_Example, when it's time to visualize the generated conformations with nglview it shows a movie with 200 frames but all equals. Checking the PDB I see that all 200 generated conformations are identical, even if selected in different clusters. It occurs to me is that the folder "checkpoint" is in reality empty, therefore when selecting one of the steps, it selects only the first frame (corresponding to the original PDB asp7.pdb) and copies it 200 times as they were different conformations.
I've also changed the parameter checkpoint_step to 10, but still the corresponding "checkpoint" folder remains empty.
How can I resolve this issue?
Thank you very much

**Comment by TobiasLe** [comment]
When all generated structures are equal, this is typically a problem of regularization. In the tutorial I write:

"Currently we use a regularization constant parameters.l2_reg_constant = 10.0. The regularization constant influences the complexity of the network and the map. A high regularization constant will result in a smooth map with little details. A small regularization constant will result in a rougher more detailed map."

I guess I should add to the tutorial, that the regularization also influences the generated conformations. With a low regularization constant generated structures along a path can be changing quite abruptly. With a higher regularization constant the generated structures along a path change more smoothly. In the extreme case, a high regularization constant can force the complexity of the network to become so limited that it will always generate the same conformation no matter what input is given. 

Try to set the parameters.l2_reg_constant to something small like 0.001 and let me know if that solved your problem.

I am not so sure about the missing checkpoint files. If you were able to run the "Generate Molecular Conformations" part, then you must have already loaded a checkpoint in the previous section. So I think they must have been written somewhere.

**Comment by Monte95** [comment]
It works just fine with parameters.l2_reg_constant set to 0.001 . Previously I tried to lower the value, but never below 5.0 . Thank you very much
