### ISSUE TITLE
Locating reference structure in histogram2D

### ISSUE THREAD

**Issue by Monte95** [AG-Peter/encodermap#9]
Hello again @TobiasLe! I am trying to retrieve the position of the reference protein structure specified in `structure_path` in the 2D histogram ( `hist, xedges, yedges = np.histogram2d(projected[:, 0], projected[:, 1], bins=100)` ) but I cannot figure out how to do it.
Is there a way to track the reference structure during the encoding part of Encodermap, directly into `projected`?
Thank you again!

**Comment by TobiasLe** [comment]
Hi, I'm not sure I understand your question, but I will try to answer anyway. The points in the `projected` array are in the same order as they are in the input data. E.g. if you want to know where the fifth structure in your input data is projected to, you simply need to extract the fifth point in the `projected` array.
